pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.aliyun.com/repository/public' }
        maven { url = 'https://maven.aliyun.com/repository/central' }
        maven { url = 'https://maven.minecraftforge.net/' }
    }
}

rootProject.name = 'cme_fix'
